In [1]:
import numpy as np
import pandas as pd

In [2]:
stm_oct_df = pd.read_csv('x_train_2.csv',encoding='utf-8')
type(stm_oct_df)
stm_oct_df.head(20)
stm_oct_df.info

<bound method DataFrame.info of           ตอบ    พยาบาล        คน       ใช่       มอง   ส่วนตัว    ข้อมูล  \
0    0.028417  0.061662  0.018170  0.012264  0.017077  0.018660  0.024986   
1    0.000000  0.000000  0.009187  0.000000  0.000000  0.000000  0.000000   
2    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.013074   
3    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.059177   
4    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7    0.000000  0.000000  0.006890  0.006201  0.000000  0.000000  0.000000   
8    0.000000  0.000000  0.036340  0.000000  0.000000  0.000000  0.000000   
9    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10   0.000000  0.000000  0.003017  0.004073  0.000000  0.000000  0.000000   
11   0.000000  0.000000  0.000000  0.000000 

In [3]:
stm_oct_df.head(5)

ตอบ    พยาบาล        คน       ใช่       มอง  ส่วนตัว    ข้อมูล  \
0  0.028417  0.061662  0.018170  0.012264  0.017077  0.01866  0.024986   
1  0.000000  0.000000  0.009187  0.000000  0.000000  0.00000  0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.013074   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.059177   
4  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.000000   

       จริง       ถาม        ทำ  ...   ระงับ  ไล่เบี้ย  ยุ่งยาก  close  bank  \
0  0.013557  0.010089  0.018543  ...       0         0        0      0     0   
1  0.013709  0.000000  0.000000  ...       0         0        0      0     0   
2  0.000000  0.010558  0.000000  ...       0         0        0      0     0   
3  0.000000  0.000000  0.000000  ...       0         0        0      0     0   
4  0.000000  0.000000  0.017384  ...       0         0        0      0     0   

   account  company  Kasikorn  ถอนเงิน  หุ้น  
0        0        0         0        0     0  
1        0        0         0        0     0  
2        0        0         0        0     0  
3        0        0         0        0     0  
4        0        0         0        0     0  

[5 rows x 366 columns]

In [4]:
stm_oct_df.tail(5)

ตอบ    พยาบาล        คน  ใช่  มอง  ส่วนตัว  ข้อมูล      จริง  ถาม  \
112  0.0  0.022377  0.013188  0.0  0.0      0.0     0.0  0.000000  0.0   
113  0.0  0.000000  0.000000  0.0  0.0      0.0     0.0  0.000000  0.0   
114  0.0  0.000000  0.000000  0.0  0.0      0.0     0.0  0.000000  0.0   
115  0.0  0.000000  0.000000  0.0  0.0      0.0     0.0  0.035886  0.0   
116  0.0  0.000000  0.000000  0.0  0.0      0.0     0.0  0.000000  0.0   

           ทำ  ...   ระงับ  ไล่เบี้ย  ยุ่งยาก  close  bank  account  company  \
112  0.008973  ...       0         0        0      0     0        0        0   
113  0.029279  ...       0         0        0      0     0        0        0   
114  0.030906  ...       0         0        0      0     0        0        0   
115  0.000000  ...       0         0        0      0     0        0        0   
116  0.000000  ...       0         0        0      0     0        0        0   

     Kasikorn  ถอนเงิน  หุ้น  
112         0        0     0  
113         0        0     0  
114         0        0     0  
115         0        0     0  
116         0        0     0  

[5 rows x 366 columns]

In [5]:
stm_label_df = pd.read_csv('y_train.csv',encoding='utf-8',header=None)

In [6]:
stm_label_df.head(5)

0
0  negative
1  negative
2  positive
3  negative
4  negative

In [7]:
stm_oct_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Columns: 366 entries, ตอบ to หุ้น
dtypes: float64(293), int64(73)
memory usage: 334.6 KB


In [8]:
stm_oct_df.columns

Index(['ตอบ', 'พยาบาล', 'คน', 'ใช่', 'มอง', 'ส่วนตัว', 'ข้อมูล', 'จริง', 'ถาม',
       'ทำ',
       ...
       'ระงับ', 'ไล่เบี้ย', 'ยุ่งยาก', 'close', 'bank', 'account', 'company',
       'Kasikorn', 'ถอนเงิน', 'หุ้น'],
      dtype='object', length=366)

In [9]:
stm_oct_df.index

RangeIndex(start=0, stop=117, step=1)

In [10]:
stm_feature_name = stm_oct_df.columns

In [11]:
stm_feature_name

Index(['ตอบ', 'พยาบาล', 'คน', 'ใช่', 'มอง', 'ส่วนตัว', 'ข้อมูล', 'จริง', 'ถาม',
       'ทำ',
       ...
       'ระงับ', 'ไล่เบี้ย', 'ยุ่งยาก', 'close', 'bank', 'account', 'company',
       'Kasikorn', 'ถอนเงิน', 'หุ้น'],
      dtype='object', length=366)

In [12]:
stm_label_df = pd.read_csv('y_train.csv',encoding='utf-8',header=None)

In [13]:
stm_label_df.head(5)

0
0  negative
1  negative
2  positive
3  negative
4  negative

In [14]:
X = stm_oct_df.values

In [15]:
print(X)

[[ 0.028417  0.061662  0.01817  ...,  0.        0.        0.      ]
 [ 0.        0.        0.009187 ...,  0.        0.        0.      ]
 [ 0.        0.        0.       ...,  0.        0.        0.      ]
 ..., 
 [ 0.        0.        0.       ...,  0.        0.        0.      ]
 [ 0.        0.        0.       ...,  0.        0.        0.      ]
 [ 0.        0.        0.       ...,  0.        0.        0.      ]]


In [16]:
y = stm_label_df.values.ravel()

In [17]:
print(y)

['negative' 'negative' 'positive' 'negative' 'negative' 'positive'
 'positive' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'negative' 'positive' 'negative' 'negative' 'positive' 'negative'
 'positive' 'positive' 'negative' 'positive' 'negative' 'positive'
 'negative' 'positive' 'negative' 'positive' 'negative' 'negative'
 'negative' 'positive' 'positive' 'positive' 'negative' 'positive'
 'positive' 'positive' 'negative' 'negative' 'negative' 'negative'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'positive' 'negative'
 'negative' 'negative' 'positive' 'positive' 'positive' 'positive'
 'positive' 'negative' 'negative' 'negative' 'negative' 'positive'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negat

In [18]:
#import 
from sklearn import preprocessing

In [19]:
#instantiate
X_scaled = preprocessing.scale(stm_oct_df.values)

In [20]:
print(X_scaled)

[[ 3.81067567  8.42029146  1.79464811 ...,  0.          0.          0.        ]
 [-0.23517304 -0.19300253  0.75277769 ...,  0.          0.          0.        ]
 [-0.23517304 -0.19300253 -0.31275314 ...,  0.          0.          0.        ]
 ..., 
 [-0.23517304 -0.19300253 -0.31275314 ...,  0.          0.          0.        ]
 [-0.23517304 -0.19300253 -0.31275314 ...,  0.          0.          0.        ]
 [-0.23517304 -0.19300253 -0.31275314 ...,  0.          0.          0.        ]]


In [21]:
X_normalized = preprocessing.normalize(stm_oct_df, norm='l1')

In [22]:
print(X_normalized)

[[ 0.0990374   0.21490109  0.06332511 ...,  0.          0.          0.        ]
 [ 0.          0.          0.03816531 ...,  0.          0.          0.        ]
 [ 0.          0.          0.         ...,  0.          0.          0.        ]
 ..., 
 [ 0.          0.          0.         ...,  0.          0.          0.        ]
 [ 0.          0.          0.         ...,  0.          0.          0.        ]
 [ 0.          0.          0.         ...,  0.          0.          0.        ]]


In [23]:
normalizer = preprocessing.Normalizer().fit(stm_oct_df)

In [24]:
X

array([[ 0.028417,  0.061662,  0.01817 , ...,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.009187, ...,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,  0.      ],
       ..., 
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,  0.      ]])

In [25]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_normalized)

In [26]:
type(tf_transformer)

sklearn.feature_extraction.text.TfidfTransformer

In [27]:
X_train_tf = tf_transformer.transform(stm_oct_df)

In [28]:
X_train_tf.shape

(117, 366)

In [29]:
X_test = pd.read_csv('x_test_2.csv',encoding='utf-8')

In [30]:
X_test.shape

(117, 366)

In [31]:
X_test.values

array([[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,  0.      ],
       ..., 
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.081761],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,  0.      ]])

In [32]:
X_feature_test = X_test.values

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
clf_model6 = RandomForestClassifier()

In [35]:
#fit
clf_model6.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [36]:
print(clf_model6.predict(X_test))

['positive' 'positive' 'positive' 'negative' 'positive' 'negative'
 'positive' 'negative' 'negative' 'negative' 'negative' 'positive'
 'negative' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'negative' 'negative' 'negative' 'positive' 'positive'
 'positive' 'negative' 'negative' 'positive' 'negative' 'positive'
 'negative' 'negative' 'negative' 'negative' 'positive' 'positive'
 'negative' 'negative' 'positive' 'negative' 'negative' 'positive'
 'negative' 'positive' 'positive' 'negative' 'positive' 'negative'
 'negative' 'negative' 'negative' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'negative' 'positive'
 'negative' 'negative' 'negative' 'negative' 'negative' 'positive'
 'negative' 'negative' 'positive' 'negative' 'negative' 'negative'
 'positive' 'positive' 'negative' 'negative' 'negative' 'negative'
 'positive' 'negative' 'positive' 'positive' 'negative' 'posit

In [37]:
x_pred_class = clf_model6.predict(X_test)

In [38]:
from sklearn import metrics

print(metrics.accuracy_score(stm_label_df.values.ravel(), x_pred_class))

0.581196581197


In [39]:
print(metrics.confusion_matrix(stm_label_df.values.ravel(), x_pred_class))

[[32 28]
 [21 36]]


In [40]:
print(metrics.accuracy_score(stm_label_df.values.ravel(), x_pred_class))

0.581196581197


In [41]:
print(metrics.recall_score(stm_label_df.values.ravel(), x_pred_class))

C:\Users\Itsagun\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1008: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if pos_label not in present_labels:


ValueError: pos_label=1 is not a valid label: array(['negative', 'positive'], 
      dtype='<U8')

In [42]:
confusion = metrics.confusion_matrix(stm_label_df.values.ravel(), x_pred_class)
TP = confusion[1, 1]
TN = confusion[0, 0]
FP = confusion[0, 1]
FN = confusion[1, 0]

In [43]:
print(TP / float(TP + FP))
print(metrics.precision_score(stm_label_df.values.ravel(), x_pred_class))

0.5625


C:\Users\Itsagun\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1008: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if pos_label not in present_labels:


ValueError: pos_label=1 is not a valid label: array(['negative', 'positive'], 
      dtype='<U8')

In [44]:
from sklearn.cross_validation import cross_val_score

clf = RandomForestClassifier()
scores = cross_val_score(clf, X_normalized, stm_label_df.values.ravel(), cv=10, scoring='accuracy')
print(scores)

C:\Users\Itsagun\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


[ 0.58333333  0.75        0.66666667  0.5         0.75        0.66666667
  0.58333333  0.45454545  0.54545455  0.45454545]


In [45]:
from sklearn.metrics import classification_report

print(classification_report(stm_label_df.values.ravel(), x_pred_class))

             precision    recall  f1-score   support

   negative       0.60      0.53      0.57        60
   positive       0.56      0.63      0.60        57

avg / total       0.58      0.58      0.58       117

